stages:
  - build

compile_documentation:
  stage: build
  image: tianon/latex
  script:
    - apt-get update -qy
    - apt-get install -y python-pygments
    - latexmk -pdf -shell-escape Prezentacija.tex
    - cp Prezentacija.pdf ..
  artifacts:
    paths:
      - Prezentacija.pdf